

##### Trial code

```{r}
library(jsonlite)
library(emdbook) # for dbetabinom
```

Plots to help us understand the underlying beta's we'll use in betabinoms:
```{r}
# Exploratory plots of beta shape values
y=seq(0,1,by=0.0001)
plot(y,dbeta(y,shape1=1,shape2=1000),type='l',xlim=c(0,0.1),ylim=c(0,50),col=1)
points(y,dbeta(y,shape1=2,shape2=100),type='l',col=2)
points(y,dbeta(y,shape1=1.2,shape2 =2),type='l',col=3)
```

Code for making assingments:
```
# Define all clusters
geodist_cats<-expand.grid(AFR=seq(0,3),EUR=seq(0,3),SAS=seq(0,3),EAS=seq(0,3),AMR=seq(0,3))

# The per cluster loglikelihood function
loglikelihood_perclust4<-function(x,n,c){
  if(c==0){
    if(x==0)
      return(log(1))
    else
      return(log(0))
  }
  if(c==1)
    return(dbetabinom(x,size=n,shape1=1,shape2=1000,log=TRUE))
  if(c==2)
    return(dbetabinom(x,size=n,shape1=2,shape2=100,log=TRUE))
  if(c==3)
    return(dbetabinom(x,size=n,shape1=1.2,shape2=2,log=TRUE))
}

# The likelihood for a cluster configuration
loglikelihood_clust4<-function(clustvec,xobs,nobs){
  # clustvec is a vector of form (0,1,1,0,2) and must have same dimension as xobs,nobs

  # initalize number of pops and logL
  npops<-length(xobs)
  logL<-0
  
  # cycle through pops computing loglikelihood 
  for(i in seq(1,npops)){
    logL<-logL+loglikelihood_perclust4(xobs[i],nobs[i],clustvec[i])
  }
  return(logL)
}

geodist_assign4<-function(xobs,nobs,geodist_cats){
  # Compute log likelihoods and get category assignment
  loglik_geodist_cats<-apply(geodist_cats,1,loglikelihood_clust4,xobs=xobs,nobs=nobs)
  return(which.max(loglik_geodist_cats))
}

```

Code for grapping some test data
```

# Grab a random SNP
get_snv_data<-function(){
  
  x<-fromJSON("http://popgen.uchicago.edu/ggv_api/freq_table?data=%221000genomes_phase3_table%22&random_snp=True")
  # Transform to superpop count data
  # Set up 1000 Genomes groups
  sg_ids<-factor(c(1,5,3,5,1,1,2,2,5,2,2,4,2,1,4,3,4,1,5,3,3,5,3,4,4,5),labels=c("AFR","EUR","SAS","EAS","AMR"))
  nvec=tapply(as.numeric(x$nobs),sg_ids,sum)
  xvec=tapply(as.numeric(x$xobs),sg_ids,sum)
  return(data.frame(xvec,nvec))
}
```

Test run
```{r}
# 
x<-get_snv_data()
print(x)
# Make a geodist assignment!
geodist_id<-geodist_assign4(x$xvec,x$nvec,geodist_cats)
print(geodist_cats[geodist_id,])

```
